### ISSUE TITLE
Needs Comments in the Code

### ISSUE THREAD

**Issue by polple** [Android2771/cbz-exploder#1]
Comments in code serve as documentation, aiding understanding for developers who maintain or collaborate on the codebase. They clarify logic, provide context, and explain complex algorithms or decisions. Well-commented code fosters readability, accelerates troubleshooting, and facilitates future modifications, ultimately enhancing the code's reliability and maintainability.

**Comment by Android2771** [comment]
But clean code book told me not to. Checkmate!!!!

**Comment by polple** [comment]
They were wrong. Checkmate no u

**Comment by Android2771** [comment]
So real. I feel so checkmated rn
